### ISSUE TITLE
Convert the jupyter notebooks into runnable python scripts

### ISSUE THREAD

**Issue by sonalranjit** [CivicTechTO/toronto-bids#8]
- Jupyter notebooks are great in terms of showcasing a proof of concept etc. but if we want to scrape regularly then we should convert these notebooks into a python module

**Comment by Arpanio** [comment]
I can pick this up starting tomorrow evening

**Comment by Arpanio** [comment]
Worked on this for an hour, but I'm on a windows machine and there are issues with Selenium. I'll change tracks to fixing the setup issues on Windows first.

If someone on a Mac or Linux wants to take this up, please feel free.

**Comment by Arpanio** [comment]
Worked around the Selenium issues on Windows by setting up WSL2 and targeting development on Ubuntu.

I've managed to get most of `rfp_scrape.ipynb` ported to `rfp_scrape.py`. The web scraping starts, a Chrome window pops up, and then the scraping stops with no error messages. I'm currently working on troubleshooting that.

We'll probably want to target a headless version of Selenium if we want to deploy and run on a tiny Linux VM. I'm planning on expanding the scope of this issue to include that, but might back out and just do a lift-and-shift port if it turns out to be too complex and track the headless feature separately.

**Comment by AcharyaS97** [comment]
Sorry i've been meaning to communicate that I've been putting some time into this. I got the scraper running on my Windows 11 machine. It gets to the main Ariba page for the City of Toronto but it fails to parse the table of RFPs after the fact. Still haven't figured out why.

**Comment by Arpanio** [comment]
Selenium is pretty cool, but it looks like it requires a bunch of environment setup for things to work smoothly.

With Windows 11, you should be able to setup WSL. I think that would be the best way to go, since Selenium is more compliant with Linux systems and there's going to be lesser setup issues if we just stick to MacOS and Ubuntu. [These instructions](https://github.com/CivicTechTO/toronto-bids/issues/11#issuecomment-1465067902) worked for me and allowed me to continue development using vscode like usual.

**Comment by Arpanio** [comment]
I had a chat with Alex. He's also made significant progress into converting the notebooks into python files, while removing platform-specific stuff. He's testing some stuff before raising a PR.
